/**
 * ボスマスタ（auto-generated by tools/sync_csv_json.js — 直接編集不要）
 * 編集方法:
 *   data/bosses.csv を修正 → node tools/sync_csv_json.js csv-to-json
 *   data/bosses.json を修正 → node tools/sync_csv_json.js json-to-csv
 */
export const BOSS_DEFS = {
  'boss-ch1': {
    id: 'boss-ch1',
    name: 'ゴースト・上杉謙信',
    hp: 55, phy: 17, int: 6, agi: 6, imgId: 425,
    initialShield: 0,
    intentRota: [
      { kind: 'guard', value: 12 },
      { kind: 'attack', phyPct: 115 },
      { kind: 'attack', phyPct: 110 },
      { kind: 'special', pct: 16 },
    ],
  },
  'boss-hl': {
    id: 'boss-hl',
    name: 'ゴースト・楊貴妃',
    hp: 81, phy: 18, int: 10, agi: 8, imgId: 435,
    initialShield: 0,
    intentRota: [
      { kind: 'attack', phyPct: 90 },
      { kind: 'guard', value: 14 },
      { kind: 'attackBleed', phyPct: 90, bleedStacks: 2 },
      { kind: 'special', pct: 14 },
      { kind: 'buffSelf', phyAdd: 4, intAdd: 2 },
    ],
  },
  'boss-ch2': {
    id: 'boss-ch2',
    name: 'ゴースト・ナポレオン',
    hp: 138, phy: 20, int: 14, agi: 8, imgId: 445,
    initialShield: 0,
    intentRota: [
      { kind: 'attackPoison', phyPct: 105, poisonStacks: 2 },
      { kind: 'guard', value: 14 },
      { kind: 'attackIntDouble', intPct: 105 },
      { kind: 'special', pct: 22 },
      { kind: 'buffSelf', phyAdd: 4, intAdd: 3 },
    ],
  },
  'boss-ch3': {
    id: 'boss-ch3',
    name: 'ゴースト・リンカーン',
    hp: 185, phy: 21, int: 17, agi: 10, imgId: 505,
    initialShield: 24,
    phases: [
      {
        // フェーズ 1
        hpThresholdPct: 50,
        intentRota: [
          { kind: 'attack', phyPct: 95 },
          { kind: 'attackInt', intPct: 95 },
          { kind: 'guard', value: 16 },
          { kind: 'special', pct: 18 },
          { kind: 'buffSelf', phyAdd: 4, intAdd: 4 },
        ],
      },
      {
        // フェーズ 2
        hpThresholdPct: 0,
        intentRota: [
          { kind: 'attack', phyPct: 140 },
          { kind: 'special', pct: 28 },
          { kind: 'attackInt', intPct: 140 },
          { kind: 'special', pct: 28 },
          { kind: 'attackDouble', phyPct: 100 },
        ],
      },
    ],
  },
  // ─── 章間レイド ──────────────────────────────────────────────────
  // 「ヨシュカ」初代レイド（弱すぎて1日で討伐された通称「よしこ」）の再現。
  // 章1クリア後に幕間で出現。HP極小・火力激低。報酬は微妙な GUM のみ。
  'boss-yoshiko': {
    id: 'boss-yoshiko',
    name: 'ヨシュカ（よしこ）',
    hp: 18, phy: 4, int: 4, agi: 6, imgId: 171,
    initialShield: 0,
    intentRota: [
      { kind: 'attack', phyPct: 50 },
      { kind: 'guard', value: 4 },
      { kind: 'attack', phyPct: 60 },
    ],
  },
  // 「ヨシュカ・チョコ」2nd レイド（強すぎて時間切れまで倒し切れず）の再現。
  // 章2クリア後の幕間。HP 999・初期シールド30 で討伐不能。
  // 30 ターン経過で「耐久勝利」扱いとなり、報酬「チョコ片」（cardChocoFragment）獲得。
  'boss-yoshiko-choco': {
    id: 'boss-yoshiko-choco',
    name: 'ヨシュカ・チョコ（討伐不能）',
    hp: 999, phy: 14, int: 12, agi: 8, imgId: 425,
    initialShield: 30,
    enduranceTurns: 30, // main.js が turn 数をチェックして勝利扱いに
    intentRota: [
      { kind: 'guard', value: 8 },
      { kind: 'attack', phyPct: 80 },
      { kind: 'attackBleed', phyPct: 70, bleedStacks: 1 },
      { kind: 'guard', value: 6 },
      { kind: 'attackInt', intPct: 75 },
    ],
  },

  'boss-troy': {
    id: 'boss-troy',
    name: 'ディープ・ヨシュカ',
    hp: 240, phy: 27, int: 22, agi: 14, imgId: 171,
    initialShield: 0,
    phases: [
      {
        // フェーズ 1
        hpThresholdPct: 45,
        intentRota: [
          { kind: 'guard', value: 20 },
          { kind: 'attack', phyPct: 115 },
          { kind: 'attackInt', intPct: 115 },
          { kind: 'buffSelf', phyAdd: 5, intAdd: 4 },
          { kind: 'special', pct: 20 },
          { kind: 'attackDouble', phyPct: 95 },
        ],
      },
      {
        // フェーズ 2
        hpThresholdPct: 0,
        intentRota: [
          { kind: 'attackDouble', phyPct: 112 },
          { kind: 'attackPoison', phyPct: 130, poisonStacks: 3 },
          { kind: 'special', pct: 28 },
          { kind: 'attackIntDouble', intPct: 115 },
          { kind: 'attackDouble', phyPct: 105 },
          { kind: 'guard', value: 10 },
        ],
      },
    ],
  },
};
