/**
 * ボスマスタ（auto-generated by tools/sync_csv_json.js — 直接編集不要）
 * 編集方法:
 *   data/bosses.csv を修正 → node tools/sync_csv_json.js csv-to-json
 *   data/bosses.json を修正 → node tools/sync_csv_json.js json-to-csv
 */
export const BOSS_DEFS = {
  'boss-ch1': {
    id: 'boss-ch1',
    name: 'ゴースト・上杉謙信',
    hp: 65, phy: 17, int: 6, agi: 6, imgId: 425,
    initialShield: 0,
    intentRota: [
      { kind: 'guard', value: 12 },
      { kind: 'attack', phyPct: 115 },
      { kind: 'attack', phyPct: 110 },
      { kind: 'special', pct: 16 },
    ],
  },
  'boss-hl': {
    id: 'boss-hl',
    name: 'ゴースト・楊貴妃',
    hp: 90, phy: 18, int: 10, agi: 8, imgId: 435,
    initialShield: 0,
    intentRota: [
      { kind: 'attack', phyPct: 105 },
      { kind: 'guard', value: 14 },
      { kind: 'attackBleed', phyPct: 95, bleedStacks: 2 },
      { kind: 'special', pct: 14 },
      { kind: 'buffSelf', phyAdd: 4, intAdd: 2 },
    ],
  },
  'boss-ch2': {
    id: 'boss-ch2',
    name: 'ゴースト・ナポレオン',
    hp: 115, phy: 20, int: 14, agi: 8, imgId: 445,
    initialShield: 0,
    intentRota: [
      { kind: 'attackPoison', phyPct: 105, poisonStacks: 2 },
      { kind: 'guard', value: 14 },
      { kind: 'attackIntDouble', intPct: 105 },
      { kind: 'special', pct: 22 },
      { kind: 'buffSelf', phyAdd: 4, intAdd: 3 },
    ],
  },
  'boss-ch3': {
    id: 'boss-ch3',
    name: 'ゴースト・リンカーン',
    hp: 200, phy: 24, int: 20, agi: 10, imgId: 505,
    initialShield: 30,
    phases: [
      {
        // フェーズ 1
        hpThresholdPct: 50,
        intentRota: [
          { kind: 'attack', phyPct: 105 },
          { kind: 'attackInt', intPct: 105 },
          { kind: 'guard', value: 16 },
          { kind: 'special', pct: 20 },
          { kind: 'buffSelf', phyAdd: 5, intAdd: 5 },
        ],
      },
      {
        // フェーズ 2
        hpThresholdPct: 0,
        intentRota: [
          { kind: 'attack', phyPct: 140 },
          { kind: 'special', pct: 28 },
          { kind: 'attackInt', intPct: 140 },
          { kind: 'special', pct: 28 },
          { kind: 'attackDouble', phyPct: 100 },
        ],
      },
    ],
  },
  'boss-troy': {
    id: 'boss-troy',
    name: 'ディープ・ヨシュカ',
    hp: 240, phy: 27, int: 22, agi: 14, imgId: 171,
    initialShield: 0,
    phases: [
      {
        // フェーズ 1
        hpThresholdPct: 45,
        intentRota: [
          { kind: 'guard', value: 20 },
          { kind: 'attack', phyPct: 115 },
          { kind: 'attackInt', intPct: 115 },
          { kind: 'buffSelf', phyAdd: 5, intAdd: 4 },
          { kind: 'special', pct: 20 },
          { kind: 'attackDouble', phyPct: 95 },
        ],
      },
      {
        // フェーズ 2
        hpThresholdPct: 0,
        intentRota: [
          { kind: 'attackDouble', phyPct: 112 },
          { kind: 'attackPoison', phyPct: 130, poisonStacks: 3 },
          { kind: 'special', pct: 28 },
          { kind: 'attackIntDouble', intPct: 115 },
          { kind: 'attackDouble', phyPct: 105 },
          { kind: 'guard', value: 10 },
        ],
      },
    ],
  },
};
