/**
 * 敵マスタ（auto-generated by tools/sync_csv_json.js — 直接編集不要）
 * 編集方法:
 *   data/enemies.csv を修正 → node tools/sync_csv_json.js csv-to-json
 *   data/enemies.json を修正 → node tools/sync_csv_json.js json-to-csv
 */
export const ENEMY_DEFS = {
  'sn-001': {
    id: 'sn-001', name: 'クリーパー ヴェンティ',
    hp: 18, phy: 10, int: 4, agi: 6, imgId: 104,
    intentRota: [
      { kind: 'attack', phyPct: 90 },
      { kind: 'attack', phyPct: 100 },
      { kind: 'guard', value: 6 },
    ],
  },
  'sn-002': {
    id: 'sn-002', name: 'エルククローナ ヴェンティ',
    hp: 14, phy: 8, int: 6, agi: 12, imgId: 114,
    intentRota: [
      { kind: 'attack', phyPct: 80 },
      { kind: 'attack', phyPct: 110 },
    ],
  },
  'sn-003': {
    id: 'sn-003', name: 'メリッサ ヴェンティ',
    hp: 26, phy: 14, int: 4, agi: 4, imgId: 134,
    intentRota: [
      { kind: 'guard', value: 8 },
      { kind: 'attack', phyPct: 130 },
    ],
  },
  'sn-e01': {
    id: 'sn-e01', name: 'クリーパー フラペチーノ',
    hp: 28, phy: 17, int: 6, agi: 8, imgId: 106,
    intentRota: [
      { kind: 'guard', value: 12 },
      { kind: 'attack', phyPct: 115 },
      { kind: 'attack', phyPct: 110 },
    ],
  },
  'hl-001': {
    id: 'hl-001', name: 'ハートブリード ヴェンティ',
    hp: 24, phy: 12, int: 6, agi: 8, imgId: 124,
    intentRota: [
      { kind: 'attack', phyPct: 95 },
      { kind: 'attackBleed', phyPct: 75, bleedStacks: 2 },
      { kind: 'guard', value: 7 },
    ],
  },
  'hl-002': {
    id: 'hl-002', name: 'バイトバンディット ヴェンティ',
    hp: 26, phy: 16, int: 4, agi: 10, imgId: 164,
    intentRota: [
      { kind: 'attackBleed', phyPct: 90, bleedStacks: 1 },
      { kind: 'guard', value: 8 },
      { kind: 'attack', phyPct: 115 },
    ],
  },
  'hl-003': {
    id: 'hl-003', name: 'クリーパー マキアート',
    hp: 20, phy: 11, int: 9, agi: 14, imgId: 105,
    intentRota: [
      { kind: 'attack', phyPct: 85 },
      { kind: 'attack', phyPct: 90 },
      { kind: 'guard', value: 6 },
    ],
  },
  'hl-e01': {
    id: 'hl-e01', name: 'ハートブリード フラペチーノ',
    hp: 44, phy: 19, int: 7, agi: 10, imgId: 126,
    intentRota: [
      { kind: 'guard', value: 12 },
      { kind: 'attackBleed', phyPct: 110, bleedStacks: 2 },
      { kind: 'attack', phyPct: 120 },
    ],
  },
  'vp-001': {
    id: 'vp-001', name: 'カスケード ヴェンティ',
    hp: 24, phy: 13, int: 6, agi: 8, imgId: 378,
    intentRota: [
      { kind: 'attack', phyPct: 105 },
      { kind: 'attack', phyPct: 95 },
      { kind: 'guard', value: 7 },
    ],
  },
  'vp-002': {
    id: 'vp-002', name: 'ラビット ヴェンティ',
    hp: 20, phy: 11, int: 9, agi: 12, imgId: 389,
    intentRota: [
      { kind: 'attackPoison', phyPct: 75, poisonStacks: 2 },
      { kind: 'attack', phyPct: 95 },
      { kind: 'attackPoison', phyPct: 70, poisonStacks: 1 },
    ],
  },
  'vp-003': {
    id: 'vp-003', name: 'バイトバンディット グランデ',
    hp: 28, phy: 16, int: 5, agi: 8, imgId: 163,
    intentRota: [
      { kind: 'attackBleed', phyPct: 85, bleedStacks: 2 },
      { kind: 'guard', value: 8 },
      { kind: 'attack', phyPct: 110 },
    ],
  },
  'vp-e01': {
    id: 'vp-e01', name: 'カスケード フラペチーノ',
    hp: 48, phy: 20, int: 8, agi: 10, imgId: 380,
    intentRota: [
      { kind: 'attack', phyPct: 115 },
      { kind: 'guard', value: 12 },
      { kind: 'attackDouble', phyPct: 85 },
      { kind: 'buffSelf', phyAdd: 4 },
    ],
  },
  'en-301': {
    id: 'en-301', name: 'ベーグル ヴェンティ',
    hp: 34, phy: 18, int: 8, agi: 10, imgId: 184,
    intentRota: [
      { kind: 'attack', phyPct: 115 },
      { kind: 'attackDouble', phyPct: 85 },
      { kind: 'guard', value: 12 },
    ],
  },
  'en-302': {
    id: 'en-302', name: 'ラブレター マキアート',
    hp: 28, phy: 6, int: 20, agi: 8, imgId: 401,
    intentRota: [
      { kind: 'attackInt', intPct: 120 },
      { kind: 'healSelf', pct: 22 },
      { kind: 'attackInt', intPct: 95 },
      { kind: 'buffSelf', intAdd: 4 },
    ],
  },
  'en-303': {
    id: 'en-303', name: 'ラビット マキアート ドッピオ',
    hp: 32, phy: 15, int: 13, agi: 14, imgId: 395,
    intentRota: [
      { kind: 'attack', phyPct: 85 },
      { kind: 'buffSelf', phyAdd: 5 },
      { kind: 'attack', phyPct: 120 },
    ],
  },
  'en-e01': {
    id: 'en-e01', name: 'ベーグル フラペチーノ',
    hp: 62, phy: 22, int: 10, agi: 12, imgId: 186,
    intentRota: [
      { kind: 'attackDouble', phyPct: 90 },
      { kind: 'guard', value: 16 },
      { kind: 'special', pct: 18 },
      { kind: 'buffSelf', phyAdd: 4 },
    ],
  },
  'tr-001': {
    id: 'tr-001', name: 'カメレオン グランデ',
    hp: 36, phy: 18, int: 10, agi: 16, imgId: 411,
    intentRota: [
      { kind: 'buffSelf', phyAdd: 6 },
      { kind: 'guard', value: 12 },
      { kind: 'attack', phyPct: 130 },
      { kind: 'attackPoison', phyPct: 80, poisonStacks: 2 },
      { kind: 'attack', phyPct: 125 },
    ],
  },
  'tr-002': {
    id: 'tr-002', name: 'ラブレター グランデ',
    hp: 30, phy: 8, int: 24, agi: 12, imgId: 399,
    intentRota: [
      { kind: 'attackInt', intPct: 130 },
      { kind: 'buffSelf', intAdd: 5 },
      { kind: 'healSelf', pct: 28 },
      { kind: 'attackInt', intPct: 140 },
      { kind: 'attackIntDouble', intPct: 90 },
    ],
  },
  'tr-003': {
    id: 'tr-003', name: 'ベーグル グランデ',
    hp: 46, phy: 22, int: 8, agi: 8, imgId: 183,
    intentRota: [
      { kind: 'guard', value: 16 },
      { kind: 'attackDouble', phyPct: 90 },
      { kind: 'guard', value: 10 },
      { kind: 'attack', phyPct: 125 },
      { kind: 'special', pct: 14 },
    ],
  },
  'tr-e01': {
    id: 'tr-e01', name: 'カメレオン フラペチーノ ドッピオ',
    hp: 72, phy: 27, int: 16, agi: 20, imgId: 418,
    intentRota: [
      { kind: 'guard', value: 18 },
      { kind: 'buffSelf', phyAdd: 6, intAdd: 4 },
      { kind: 'attackPoison', phyPct: 115, poisonStacks: 2 },
      { kind: 'attackBleed', phyPct: 105, bleedStacks: 2 },
      { kind: 'attackDouble', phyPct: 100 },
      { kind: 'special', pct: 16 },
    ],
  },
};
