/**
 * ヒーローマスタ（auto-generated by tools/sync_csv_json.js — 直接編集不要）
 * 編集方法:
 *   data/heroes.csv を修正 → node tools/sync_csv_json.js csv-to-json
 *   data/heroes.json を修正 → node tools/sync_csv_json.js json-to-csv
 *
 * data/heroes.json は配列形式で、CSV と同じ並びで出力される（並び順を保持）。
 */
import { img } from "./constants.js";

export const HERO_ROSTER = [
  {
    heroId: 1002,
    nameJa: "甲斐姫",
    rarity: "common",
    hpMax: 70,
    basePhy: 10,
    baseInt: 8,
    baseAgi: 12,
    passiveKey: "kaihime",
    passiveName: "浪切",
    passiveDesc: "スキルカード使用後に50%の確率で発動・先頭の敵にPHYの50%追加ダメージ",
    img: () => img("Image/Heroes/1002.png"),
  },
  {
    heroId: 1001,
    nameJa: "コナン・ドイル",
    rarity: "common",
    hpMax: 85,
    basePhy: 7,
    baseInt: 23,
    baseAgi: 8,
    passiveKey: "doyle",
    passiveName: "シャーロック・ホームズ",
    passiveDesc: "HPが70%未満になったとき1回だけ発動・INT +3",
    img: () => img("Image/Heroes/1001.png"),
  },
  {
    heroId: 1003,
    nameJa: "張遼",
    rarity: "common",
    hpMax: 85,
    basePhy: 15,
    baseInt: 6,
    baseAgi: 10,
    passiveKey: "zhang",
    passiveName: "遼来遼来",
    passiveDesc: "被ダメージ後に50%の確率で発動・先頭の敵にPHYの20%追加ダメージ",
    img: () => img("Image/Heroes/1003.png"),
  },
];

/** ID 検索用ルックアップ */
export const HERO_DEFS = Object.fromEntries(HERO_ROSTER.map(h => [String(h.heroId), h]));
